jwt:
  secret: ${JWT_SECRET}

server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/supportportal?createDatabaseIfNotExist=true&
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
